### ISSUE TITLE
Fourm API

### ISSUE THREAD

**Issue by Bob620** [aheadley/python-crunchyroll#6]
I was wondering if the API also extended into the forums, and if it does if and when this interface might be extended for them. Along with that Messaging support possibly.

**Comment by aheadley** [comment]
There is a very small amount of forum functionality that could be added to the AJAX API (see [cr.js](http://static.ak.crunchyroll.com/js/20150610174516.4dc6ff1443f126fad6608fddbc8a1e0a/jquery/cr.js)) and full functionality could potential be added to the scraper API but I have no plans to do either of those.
