### ISSUE TITLE
setup.py's tests are failing

### ISSUE THREAD

**Issue by SamusAranX** [aheadley/python-crunchyroll#7]
Here's the output that I get when running `python setup.py test` on a freshly cloned version of python-crunchyroll in OS X 10.10.4:

>running test
>running egg_info
>writing requirements to crunchyroll.egg-info/requires.txt
>writing crunchyroll.egg-info/PKG-INFO
>writing top-level names to crunchyroll.egg-info/top_level.txt
>writing dependency_links to crunchyroll.egg-info/dependency_links.txt
>reading manifest file 'crunchyroll.egg-info/SOURCES.txt'
>writing manifest file 'crunchyroll.egg-info/SOURCES.txt'
>running build_ext
>test_list_media (tests.test_integration.TestIntegration) ... ERROR
>test_login (tests.test_integration.TestIntegration) ... skipped 'Login credentials not available'
>test_login_fail (tests.test_integration.TestIntegration) ... ERROR
>test_search (tests.test_integration.TestIntegration) ... ERROR
>
>======================================================================
>ERROR: test_list_media (tests.test_integration.TestIntegration)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/Users/peterwunder/GitHub/python-crunchyroll/tests/test_integration.py", line 50, in test_list_media
>    self._media = self.api.list_media(self._series)
>AttributeError: 'TestIntegration' object has no attribute '_series'
>
>======================================================================
>ERROR: test_login_fail (tests.test_integration.TestIntegration)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/Users/peterwunder/GitHub/python-crunchyroll/tests/test_integration.py", line 43, in test_login_fail
>    self.api.login(username='example-bad-username', password='example-bad-password')
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/meta.py", line 42, in inner_func
>    self.start_session()
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/meta.py", line 182, in start_session
>    self._android_api.start_session()
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 39, in inner_func
>    req_func = self._build_request(req_method, req_url, params=kwargs)
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 137, in _build_request
>    full_params = self._get_base_params()
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 108, in _get_base_params
>    'locale':       self._get_locale(),
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 102, in _get_locale
>    return locale.getdefaultlocale()[0].replace('_', '').replace('-', '')
>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 511, in getdefaultlocale
>    return _parse_localename(localename)
>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 443, in _parse_localename
>    raise ValueError, 'unknown locale: %s' % localename
>ValueError: unknown locale: UTF-8
>
>======================================================================
>ERROR: test_search (tests.test_integration.TestIntegration)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/Users/peterwunder/GitHub/python-crunchyroll/tests/test_integration.py", line 46, in test_search
>    self._series = self.api.search_anime_series('Space Brothers')[0]
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/meta.py", line 42, in inner_func
>    self.start_session()
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/meta.py", line 182, in start_session
>    self._android_api.start_session()
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 39, in inner_func
>    req_func = self._build_request(req_method, req_url, params=kwargs)
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 137, in _build_request
>    full_params = self._get_base_params()
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 108, in _get_base_params
>    'locale':       self._get_locale(),
>  File "/Users/peterwunder/GitHub/python-crunchyroll/crunchyroll/apis/android.py", line 102, in _get_locale
>    return locale.getdefaultlocale()[0].replace('_', '').replace('-', '')
>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 511, in getdefaultlocale
>    return _parse_localename(localename)
>  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 443, in _parse_localename
>    raise ValueError, 'unknown locale: %s' % localename
>ValueError: unknown locale: UTF-8
>
>----------------------------------------------------------------------
>Ran 4 tests in 0.006s
>
>FAILED (errors=3, skipped=1)

I'm using Python 2.7.6 for this. Have you considered moving this project to Python 3, where string encodings aren't as big a clusterfuck as in Python 2?

**Comment by aheadley** [comment]
Well, that is one of the weirdest errors I've ever seen. It's not related to the string encoding, or at least, not in the usual encoding barfing way. For some reason your python install seems to be barfing when reading the locale setting. You should be able to reproduce the error with:
~~~~py
>>> import locale
>>> locale.getdefaultlocale()
('en_US', 'UTF-8')
~~~~

A quick glance suggests that your `$LANG` env var is not what python is expecting (there should be a `.` (dot) in it).


As for switching to Py3k, I originally wrote this to use in a XBMC addon, and still want to get around to finishing that at some point so I can't drop 2.x support. More could probably be done to make it compatibile with 3.x though, I haven't tested that at all.
